kind: pipeline
name: default

steps:
- name: trigger deployment
  image: drone/cli
  commands:
  - drone deploy whereismyjetpack/random-gif $DRONE_BUILD_NUM production
- name: build
  image: python:3
  when:
    target:
    - production
  commands:
  - date
  - ls
