kind: pipeline
name: default

steps:
- name: build
  image: whereismyjetpack/skaffold-kustomize:v4
  environment:
    TOKEN:
      from_secret: token
    CACERT:
      from_secret: cacert
  commands:
  - sed -i -e "s/__cacert__/$CACERT/g" /root/.kube/config
  - sed -i -e "s/__token__/$TOKEN/g" /root/.kube/config
  - skaffold build
