kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
    - export DOCKER_HOST=unix:///var/run/host.sock
    - docker login -u 'robot$random-gif' -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
    - docker build -t harbor.dsrd.libraries.psu.edu/library/random-gif:$DRONE_BUILD_NUMBER .
    - docker push harbor.dsrd.libraries.psu.edu/library/random-gif:$DRONE_BUILD_NUMBER
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock