kind: pipeline
name: default

steps:
- name: thing
  image: whereismyjetpack/skaffold-kustomize:latest
  environment:
    - DOCKER_HOST=tcp://docker:2375
  commands:
  - skaffold build

services:
- name: docker
  image: docker:dind
  privileged: true
