image: ubuntu:latest

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

stages:
  - build
  - deploy
  - backup


build:
  stage: build
  script:
    - apt-get install docker 
    - apt-get install helm
