image: docker:dind

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

variables:
  KUBERNETES_NAMESPACE_OVERWRITE: default

stages:
  - build
  - deploy
  - backup


build:
  stage: build
  script:
    - docker build -t test .
