image: docker:latest

cache:
  untracked: false
  paths: []

variables:
  # variables set in gitlab
  # DOCKER_TOKEN
  # GIT_ACCESS_TOKEN
  IMAGE_PULL_SECRETS: nexus
  GIT_ACCESS_USER: djb44
  KUBE_UTILS_URL: quay.io/dannbohn/kube-utils:latest
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REGISTRY: "nexus.ci.psu.edu:5000"
  DOCKER_USER: "deployment"
  REGISTRY_NAMESPACE: dannbohn
  TRAEFIK_STICKY_SESSIONS: "true"
  DOMAIN: qa.k8s.psu.edu

services:
- docker:dind

stages:
  - build

build:
  stage: build
  script:
    - env
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA .
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
