cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

stages:
  - build
  - deploy
  - backup

before_script:
  - git-crypt unlock

after_script:
  - git-crypt lock

build:
  stage: build
  script:
    - export HTTP_PROXY=http://proxy.aset.psu.edu:8080
    - export HTTPS_PROXY=http://proxy.aset.psu.edu:8080
    - docker build -t nexus.ci.psu.edu:5000/djb44/random:$CI_COMMIT_REF_NAME .
    - docker push nexus.ci.psu.edu:5000/djb44/random
  tags:
    - docker

stop_dev:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - helm delete random-gif-dev
  environment:
    name: dev
    action: stop

deploy_dev:
  stage: deploy
  script:
    # - env
    - helm upgrade --install random-gif-dev deploy/random-gif -f values-dev.yml --wait --set jobid=$CI_JOB_ID
  only:
    - develop
  environment:
    name: dev
    url: https://dev.random-gif.k8s.psu.edu
    on_stop: stop_dev
