image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_PULL_SECRETS: nexus
  DOCKER_REGISTRY: nexus.ci.psu.edu:5000
  REGISTRY_NAMESPACE: djb44
  DOMAIN: dev.k8s.psu.edu
  ENVIRONMENT_NAME: $CI_COMMIT_REF_SLUG

services:
- docker:dind

stages:
  - thing

thing:
  stage: thing
  image: indiehosters/git
  script:
    - git remote set-url origin $GIT_REPO_ORIGIN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME.git
    - git checkout master
    - git checkout develop
    - git checkout -b release/v9
    - git push origin --all
