image: docker:latest

cache:
  untracked: true

variables:
  KUBE_UTILS_URL: quay.io/dannbohn/kube-utils:latest
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REGISTRY: "quay.io"
  DOCKER_USER: "dannbohn+robot"
  REGISTRY_NAMESPACE: dannbohn
  TRAEFIK_STICKY_SESSIONS: "true"
  DOMAIN: dev.k8s.psu.edu

services:
- docker:dind

stages:
  - build
  - feature
  - release
  - deploy

build:
  stage: build
  script:
    - docker login -u $DOCKER_USER -p $NEXUS_TOKEN $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  dependencies: []

deploy_nonprod:
  stage: deploy
  image: $KUBE_UTILS_URL
  except:
  - master
  script:
    - deployer deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME.$DOMAIN
  dependencies: []

finish_feature:
  stage: feature
  image: $KUBE_UTILS_URL
  variables:
    CI_REPOSITORY_URL: https://djb44:$GIT_ACCESS_TOKEN@git.psu.edu/$CI_PROJECT_PATH.git
  when: manual
  only:
  - /^feature\/.*$/
  script:
  - git checkout develop
  - git merge --no-ff $CI_COMMIT_REF_NAME
  - git branch -d $CI_COMMIT_REF_NAME
  - git add . 
  - git commit -m 'finish feature $CI_COMMIT_REF_NAME'
  - git push --follow-tags $CI_REPOSITORY_URL HEAD:$CI_COMMIT_REF_NAME -q

start_release:
  variables:
    CI_REPOSITORY_URL: https://djb44:$GIT_ACCESS_TOKEN@git.psu.edu/$CI_PROJECT_PATH.git
  stage: release
  image: $KUBE_UTILS_URL
  only:
  - develop
  script:
  - version=`cat version`
  - let version=$version+1
  - git checkout -b release/$version develop
  - echo $version > version
  - git add . 
  - git commit -m 'start release $version'
  - git push --follow-tags $CI_REPOSITORY_URL HEAD:$CI_COMMIT_REF_NAME -q
  when: manual



deploy_staging:
  stage: deploy
  image: $KUBE_UTILS_URL
  only:
  - master
  script:
  - deployer deploy
  environment:
    name: staging
    url: https://staging-$CI_PROJECT_NAME.$DOMAIN
  dependencies: []

deploy_prod:
  variables:
    VANITY_DOMAIN: random-gif.psu.edu
    DOMAIN: qa.k8s.psu.edu
  when: manual
  only:
  - master
  stage: deploy
  image: $KUBE_UTILS_URL
  script:
  - deployer deploy
  environment:
    name: prod
    url: https://$CI_PROJECT_NAME.$DOMAIN
  tags:
  - prod
