image: docker:latest

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

variables:
  DOCKER_HOST: tcp://localhost:2375

services:
- docker:dind

stages:
  - build
  - deploy
  - backup


build:
  stage: build
  script:
    - docker login -u deployment -p $NEXUS_TOKEN nexus.ci.psu.edu:5000
    - docker build -t nexus.ci.psu.edu:5000/test/random .
    - docker push nexus.ci.psu.edu:5000/test/random:latest


deploy:
  stage: deploy
  image: alpine:latest

  script:
    -  curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - ./kubectl get pods
