image: docker:latest

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

variables:
  DOCKER_HOST: tcp://localhost:2375

services:
- docker:dind

stages:
  - build
  - deploy
  - backup


build:
  stage: build
  script:
    - docker login -u deployment -p $NEXUS_TOKEN nexus.ci.psu.edu:5000
    - docker build -t nexus.ci.psu.edu:5000/djb44/random:$CI_COMMIT_SHA .
    - docker push nexus.ci.psu.edu:5000/djb44/random


deploy:
  stage: deploy
  image: whereismyjetpack/build:latest

  script:
    - helm upgrade --install test deploy/random-gif --wait --set image.tag=$CI_COMMIT_SHA --set ingress.hosts={dev.random-gif.k8s.psu.edu}
  only:
    - develop
