image: docker:latest

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

variables:
  DOCKER_HOST: tcp://localhost:2375

services:
- docker:dind

stages:
  - build
  - deploy
  - backup


build:
  stage: build
  script:
    - docker build -t test .
