image: docker:latest

cache:
  untracked: true

variables:
  KUBE_UTILS_URL: quay.io/dannbohn/kube-utils:latest
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_REGISTRY: "quay.io"
  DOCKER_USER: "dannbohn+robot"
  REGISTRY_NAMESPACE: dannbohn
  TRAEFIK_STICKY_SESSIONS: "true"
  DOMAIN: dev.k8s.psu.edu

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u $DOCKER_USER -p $NEXUS_TOKEN $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG .
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  dependencies: []


deploy_nonprod:
  stage: deploy
  image: $KUBE_UTILS_URL
  except:
  - master
  script:
    - deployer deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-$CI_PROJECT_NAME.$DOMAIN
  dependencies: []

deploy_prod:
  variables:
    VANITY_DOMAIN: random-gif.psu.edu
    DOMAIN: qa.k8s.psu.edu
  when: manual
  only:
  - master
  stage: deploy
  image: $KUBE_UTILS_URL
  script:
    - envtpl deploy/random-gif.yml.tpl
    - kubectl apply -f deploy/random-gif.yml
  environment:
    name: prod
    url: https://$CI_PROJECT_NAME.$DOMAIN
