cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  untracked: true

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - export HTTP_PROXY=http://proxy.aset.psu.edu:8080
    - export HTTPS_PROXY=http://proxy.aset.psu.edu:8080
    - docker build -t nexus.ci.psu.edu:5000/djb44/random:$CI_COMMIT_REF_NAME .
    - docker push nexus.ci.psu.edu:5000/djb44/random
  tags:
    - docker

deploy_dev:
  stage: deploy
  script:
    - helm upgrade --install random-gif-$CI_COMMIT_REF_NAME deploy/random-gif -f deploy/random-gif/values-$CI_COMMIT_REF_NAME.yml --wait
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://dev.random-gif.k8s.psu.edu
