image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_PULL_SECRETS: nexus
  DOCKER_REGISTRY: nexus.ci.psu.edu:5000
  REGISTRY_NAMESPACE: djb44
  DOMAIN: dev.k8s.psu.edu

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u deployment -p $NEXUS_TOKEN $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  only:
    - develop

build_tags:
  stage: build
  script:
    - docker login -u deployment -p $NEXUS_TOKEN $DOCKER_REGISTRY
    - docker pull $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker push $DOCKER_REGISTRY/$REGISTRY_NAMESPACE/$CI_PROJECT_NAME
  only:
    - tags

deploy_version:
  stage: deploy
  image: nexus.ci.psu.edu:5000/syseng/kube-utils:latest
  script:
    - envtpl deploy/$CI_PROJECT_NAME.yml.tpl
    - kubectl apply -f deploy/$CI_PROJECT_NAME.yml
    - kubectl get deployments
  only:
    - tags
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$DOMAIN


deploy:
  stage: deploy
  image: nexus.ci.psu.edu:5000/syseng/kube-utils:latest
  script:
    - envtpl deploy/$CI_PROJECT_NAME.yml.tpl
    - kubectl apply -f deploy/$CI_PROJECT_NAME.yml
    - kubectl get deployments
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$DOMAIN
  except:
    - master
    - tags

promote_to_prod:
  variables:
    CI_COMMIT_REF_SLUG: prod
  stage: deploy
  image: nexus.ci.psu.edu:5000/syseng/kube-utils:latest
  script:
    - envtpl deploy/$CI_PROJECT_NAME.yml.tpl
    - kubectl apply -f deploy/$CI_PROJECT_NAME.yml
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME.$DOMAIN
  only:
    - tags
