version: 2
jobs:
  build:
    docker:
    - image: whereismyjetpack/python-builder:latest
    steps:
    - checkout
    - run:
       command: |
         pip install -r requirements.txt
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build
        command: |
          echo "$DOCKER_PASSWORD" | docker login --username whereismyjetpack --password-stdin
          docker build -t whereismyjetpack/random-gif:$CIRCLE_BUILD_NUM .
          docker push whereismyjetpack/random-gif:$CIRCLE_BUILD_NUM
    - run:
        name: tag
        command: |
          cd kustomize/$CIRCLE_BRANCH
          kustomize edit set image whereismyjetpack/random-gif:$CIRCLE_BUILD_NUM
          git config user.email "circleci@dannbohn.things"
          git config user.name "circleCI"
          git add kustomization.yaml
          git commit -m '[skip ci] this is a thing'
          git push -u origin $CIRCLE_BRANCH
