version: 2
jobs:
  build:
    docker:
    - image: python:3
    steps:
    - checkout
    - run:
       command: |
         pip install -r requirements.txt
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build
        command: |
          docker build -t foo . 
