---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: random-gif-feature-foo
  labels:
    app: random-gif
    ref: "feature-foo"
    user: "4"
    job_number: "9893"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: random-gif
        ref: "feature-foo"
    spec:
      containers:
      - name: random-gif
        imagePullPolicy: Always
        image: "quay.io/dannbohn/random-gif:feature-foo"
        env:
        - name: CI_COMMIT_SHA
          value: "d5d94f21557a021eb83851a3c2d2434d8eec736e"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi