apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: random-gif
  path: ingress_patch.yaml

