apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesJson6902:
- path: ingress_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: random-gif
    version: v1beta1

images:
- name: whereismyjetpack/random-gif
  newTag: "43"
